### ISSUE TITLE
请问这个是新版本的实验么

### ISSUE THREAD

**Issue by zcwhy** [SJTU-IPADS/OS-Course-Lab#10]
课程的lab和书籍官网的配套实验不一致，是以这个为准么？另外gitee上v2新版和这个也有出入，实验是以哪个为准

**Comment by sjtugjy** [comment]
官网（ https://ipads.se.sjtu.edu.cn/ospi/）的配套lab链接就是这里呀。这里是新版本的实验~

**Comment by zcwhy** [comment]
> 官网（ [https://ipads.se.sjtu.edu.cn/ospi/）的配套lab链接就是这里呀。这里是新版本的实验](https://ipads.se.sjtu.edu.cn/ospi/%EF%BC%89%E7%9A%84%E9%85%8D%E5%A5%97lab%E9%93%BE%E6%8E%A5%E5%B0%B1%E6%98%AF%E8%BF%99%E9%87%8C%E5%91%80%E3%80%82%E8%BF%99%E9%87%8C%E6%98%AF%E6%96%B0%E7%89%88%E6%9C%AC%E7%9A%84%E5%AE%9E%E9%AA%8C)~
这个lab是还在更新么，现在和旧版的还差一个lab5

**Comment by zcwhy** [comment]
> 官网（ [https://ipads.se.sjtu.edu.cn/ospi/）的配套lab链接就是这里呀。这里是新版本的实验](https://ipads.se.sjtu.edu.cn/ospi/%EF%BC%89%E7%9A%84%E9%85%8D%E5%A5%97lab%E9%93%BE%E6%8E%A5%E5%B0%B1%E6%98%AF%E8%BF%99%E9%87%8C%E5%91%80%E3%80%82%E8%BF%99%E9%87%8C%E6%98%AF%E6%96%B0%E7%89%88%E6%9C%AC%E7%9A%84%E5%AE%9E%E9%AA%8C)~


这个lab是还没有发布完么

**Comment by zcwhy** [comment]
> 官网（ [https://ipads.se.sjtu.edu.cn/ospi/）的配套lab链接就是这里呀。这里是新版本的实验](https://ipads.se.sjtu.edu.cn/ospi/%EF%BC%89%E7%9A%84%E9%85%8D%E5%A5%97lab%E9%93%BE%E6%8E%A5%E5%B0%B1%E6%98%AF%E8%BF%99%E9%87%8C%E5%91%80%E3%80%82%E8%BF%99%E9%87%8C%E6%98%AF%E6%96%B0%E7%89%88%E6%9C%AC%E7%9A%84%E5%AE%9E%E9%AA%8C)~


lab5是还没有发布么，还是新版本的只有lab0~4

**Comment by zcwhy** [comment]
> 官网（ [https://ipads.se.sjtu.edu.cn/ospi/）的配套lab链接就是这里呀。这里是新版本的实验](https://ipads.se.sjtu.edu.cn/ospi/%EF%BC%89%E7%9A%84%E9%85%8D%E5%A5%97lab%E9%93%BE%E6%8E%A5%E5%B0%B1%E6%98%AF%E8%BF%99%E9%87%8C%E5%91%80%E3%80%82%E8%BF%99%E9%87%8C%E6%98%AF%E6%96%B0%E7%89%88%E6%9C%AC%E7%9A%84%E5%AE%9E%E9%AA%8C)~

lab5是还没有发布么，还是新版本的只有lab0~4 @sjtugjy

**Comment by sjtugjy** [comment]
还会有后续的。
