### ISSUE TITLE
About cmake in ChCore-Lab3

### ISSUE THREAD

**Issue by xxyQwQ** [SJTU-IPADS/OS-Course-Lab#2]
ChCore-Lab3 中 `kernel/arch/aarch64/sched/CMakeLists.txt` 内容如下

```cmake
target_sources(${kernel_target} PRIVATE context.c.obj fpu.c.obj idle.S.obj sched.c.obj)
```

其中 `context.c` 包含 TODO，而 cmake 使用了 `context.c.obj`，造成 build 时不能更新

在 `kernel/arch/aarch64/sched/context.c` 的 `init_thread_ctx` 函数中加入调试语句可以复现这一结果

**Comment by Messith** [comment]
感谢指正！已对`CMakeLists.txt`文件进行进行修改并删除了`context.c.obj`。
