### ISSUE TITLE
Lab1: chbuild defconfig() for qemu failed

### ISSUE THREAD

**Issue by Robert-Sen** [SJTU-IPADS/OS-Course-Lab#21]
I tried to exec `./chbuild --local defconfig qemu` in lab1, but failed, it told me that
"*Generating default config file for `qemu` platform...
cp: cannot stat 'scripts/build/defconfigs/qemu.config': No such file or directory*", 
that the config for qemu is not supported yet in Lab1?

**Comment by sjtugjy** [comment]
The main branch is under changing now.
Please follow the instructions of original Lab1 branch.
https://github.com/SJTU-IPADS/OS-Course-Lab/tree/ChCore-Lab1

You could simply use `make build` for complation. 
If you choose to compile without a docker (what the local argument mean), you should type `./chbuild --local defconfig raspi3`

**Comment by Robert-Sen** [comment]
@sjtugjy I'll try, thanks!

**Comment by ToolmanP** [comment]
Even if we are in an emulator, we still use raspi3 defconfig and start qemu with raspi3 machine emulation mode. 
So we do not have this defconfig here.
```console
./chbuild --local defconfig qemu
```
This is an invalid operation. Just use make build and it's ready to go. 
Close for now.
