### ISSUE TITLE
docker image  ipads/chcore_builder arch 可以支持下arm64吗

### ISSUE THREAD

**Issue by kingcanfish** [SJTU-IPADS/OS-Course-Lab#27]
手中没有x64的机器还挺痛苦的 有空的时候可以打包个arm64的镜像 ：）

**Comment by kingcanfish** [comment]
试了一下 arm直接本地跑也行 貌似不用docker

**Comment by ToolmanP** [comment]
请问一下是devcontainer的问题
还是make某个target时候的问题

**Comment by kingcanfish** [comment]
> 请问一下是devcontainer的问题 还是make某个target时候的问题

后者,   
我现在还使用的**对应分支**上的实验，`chbuild` 默认是`run in docker`的,
但是docker image 只有amd64的，所以在arm64机器上拉不到镜像， 但是我看源码是可以以 `--local` 用本地的依赖运行的  
我理解 打包个docker 镜像跑的作用就是在 amd64 的 机器上方便交叉编译, 如果实验机器本身就是arm64的貌似不用 docker 也可以～  
可以在实验说明里面提一下～
<img width="567" alt="image" src="https://github.com/user-attachments/assets/fc9e1a06-a3c2-4242-ba2f-b574c8466cec">

**Comment by xyz2k8** [comment]
make build报错，找不到chcore_builder镜像，这个镜像在哪下载到？
```bash
os OS-Course-Lab# make build -l
chbuild: use_cgroup: , tags: 
Unable to find image 'ipads/chcore_builder:v1.8.3' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
make: *** [Makefile:23：build] 错误 125
```

**Comment by sjtugjy** [comment]
> make build报错，找不到chcore_builder镜像，这个镜像在哪下载到？
> 
> ```shell
> os OS-Course-Lab# make build -l
> chbuild: use_cgroup: , tags: 
> Unable to find image 'ipads/chcore_builder:v1.8.3' locally
> docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
> See 'docker run --help'.
> make: *** [Makefile:23：build] 错误 125
> ```

看报错，是docker pull失败，建议配置个代理。

**Comment by xyz2k8** [comment]
> > make build报错，找不到chcore_builder镜像，这个镜像在哪下载到？
> > ```shell
> > os OS-Course-Lab# make build -l
> > chbuild: use_cgroup: , tags: 
> > Unable to find image 'ipads/chcore_builder:v1.8.3' locally
> > docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
> > See 'docker run --help'.
> > make: *** [Makefile:23：build] 错误 125
> > ```
> 
> 看报错，是docker pull失败，建议配置个代理。

请问镜像放在哪个仓库？我在公网上，脚本中没有pull镜像的操作，只有创建容器操作。这个应该是需要事先pull到本地的吧。
```bash
docker_run() {
    if [ -f /.dockerenv ]; then
        # we are already in docker container
        $@
    else 
        use_cgroup=""
        if [[ $CI_RUNNER_TAGS =~ .*need_cgroup.* ]]; then
            use_cgroup="--cgroup-parent=$docker_cgroup"
        fi
        echo "chbuild: use_cgroup: $use_cgroup, tags: $CI_RUNNER_TAGS"
        test -t 1 && use_tty="-t"
        docker run -i $use_tty --rm \
            -u $(id -u ${USER}):$(id -g ${USER}) \
            -v $(pwd):$(pwd) -w $(pwd) \
            --security-opt=seccomp:unconfined \
            ipads/chcore_builder:v1.8.3 \
            $self $@
    fi
}
```

有没有dockerfile可以创建镜像？

**Comment by xyz2k8** [comment]
> make build报错，找不到chcore_builder镜像，这个镜像在哪下载到？
> 
> ```shell
> os OS-Course-Lab# make build -l
> chbuild: use_cgroup: , tags: 
> Unable to find image 'ipads/chcore_builder:v1.8.3' locally
> docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
> See 'docker run --help'.
> make: *** [Makefile:23：build] 错误 125
> ```



> > make build报错，找不到chcore_builder镜像，这个镜像在哪下载到？
> > ```shell
> > os OS-Course-Lab# make build -l
> > chbuild: use_cgroup: , tags: 
> > Unable to find image 'ipads/chcore_builder:v1.8.3' locally
> > docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
> > See 'docker run --help'.
> > make: *** [Makefile:23：build] 错误 125
> > ```
> 
> 看报错，是docker pull失败，建议配置个代理。

按照以下链接重新安装了docker，现在貌似可以了：
[清华Docker-CE](https://mirrors.tuna.tsinghua.edu.cn/help/docker-ce/)

```bash
s OS-Course-Lab# make build
chbuild: use_cgroup: , tags: 
Unable to find image 'ipads/chcore_builder:v1.8.3' locally
v1.8.3: Pulling from ipads/chcore_builder
0fb668748fc8: Pull complete 
fe1061f02714: Pull complete 
680dac4f8bc0: Downloading    382MB/456.1MB
dcaf12565bed: Download complete 
596b8c862a88: Download complete 
ec515d817d11: Download complete 
841cdf8aff29: Download complete 
b6e6289c990f: Download complete 
7a695be17089: Download complete
```

**Comment by sjtugjy** [comment]
解决了就好，就是网络的问题。docker run 命令会按需自动pull 。dockerfile也有的，不过有自定义的小tool，还是得拉取。

**Comment by sjtugjy** [comment]
@ToolmanP 逸洋，这个issue再看下后关掉吧。增强提示下local可以编译，docker pull可能存在的网络问题。

**Comment by Hi-Heng** [comment]
我遇到跟@xyz2k8 一样的问题，用@xyz2k8给的方法按照链接里面操作之后，问题依然无法解决。网络已配置代理，使用的vmware虚拟机是课程网站下载的。

**Comment by ToolmanP** [comment]
本issue在PR #41 拒绝
