### ISSUE TITLE
LAB3 Typo kernel > object > thread_env.h > PHDR MEMSZ OF

### ISSUE THREAD

**Issue by qiaoqiaoLF** [SJTU-IPADS/OS-Course-Lab#3]
There is a TYPO here
![228ad93fe43153e82be03f33c003d56](https://github.com/SJTU-IPADS/OS-Course-Lab/assets/57006825/0eab03f6-e106-425e-a5b6-eda5e1a3574c)

**Comment by sjtugjy** [comment]
Fixed now. Thanks~
