### ISSUE TITLE
The .vscode json should add a reminder

### ISSUE THREAD

**Issue by mumupika** [SJTU-IPADS/OS-Course-Lab#49]
<img width="545" alt="Screenshot 2024-10-28 at 21 28 15" src="https://github.com/user-attachments/assets/3b91e6fb-d7f4-497a-a79c-828a03a5b1a3">

In lab1 .vscode/launch.json
Some of the debugger has a different path. So in my opinion, a reminder for use `which gdb` to find the path to the miDebuggerPath is needed.

**Comment by ToolmanP** [comment]
Sorry, we only support devcontainer .vscode for now.
But your suggestion is great. Gonna add it in the further commits!
