### ISSUE TITLE
[BUG] Should use '/usr/bin/env bash' for shell interpreter

### ISSUE THREAD

**Issue by juxtaly** [SJTU-IPADS/OS-Course-Lab#52]
**报告描述**
你需要针对漏洞进行描述，其中的信息包括详细描述，构建时的系统平台，与预期不符的错误点。
NixOS 下没有 /bin/bash，解释器应换为更通用的 /usr/bin/env bash 或 /bin/sh

**复现方式**
我们该如何复现这个错误？
在 NixOS 下执行任意 shell 脚本

**截图**
如果可以的话，请附上错误截图。

**Comment by definfo** [comment]
You may refer to https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/setup-hooks/patch-shebangs.sh for a general solution.
