### ISSUE TITLE
Please remind using pip install or conda install under conda environment

### ISSUE THREAD

**Issue by mumupika** [SJTU-IPADS/OS-Course-Lab#55]
<img width="1472" alt="Screenshot 2024-10-29 at 21 42 34" src="https://github.com/user-attachments/assets/a35c8bc4-e5b2-4603-853d-37f774b11244">

<img width="1472" alt="Screenshot 2024-10-29 at 21 52 34" src="https://github.com/user-attachments/assets/e23d1f55-1ee4-48ce-a0c2-dc3bc430b4c1">

<img width="1472" alt="Screenshot 2024-10-29 at 21 53 10" src="https://github.com/user-attachments/assets/57550174-68e1-4a56-bd71-3c7223d3969c">

I found that the `make grade` has using capturer.py which using psutils. The`sudo apt` command in your [manual of getting started](https://sjtu-ipads.github.io/OS-Course-Lab/Getting-started.html) is not mentioned, which may cause error when running `make grade` under conda environment.

The environment was under `ubuntu 22.04.2 ARM 64`, with `parallel desktop` as virtual machine running on Mac M1 chips.

**Comment by ToolmanP** [comment]
I don't it's necessary to mention conda here.
