### ISSUE TITLE
Can chcore be emulated in gem5？

### ISSUE THREAD

**Issue by Emilio597** [SJTU-IPADS/OS-Course-Lab#6]
I can't see kernel print info in gem5 terminal, is it the problem of uart driver?

**Comment by Emilio597** [comment]
IPADS has a paper called treesls, which open source chcore-x86. I tried to analyze its performance in gem5 and found the problem of no output from the terminal.

**Comment by sjtugjy** [comment]
That was an out-of-service version. The mainstream has no support for gem5.
