### ISSUE TITLE
[BUG] User program may failed to run according to the md document

### ISSUE THREAD

**Issue by mumupika** [SJTU-IPADS/OS-Course-Lab#62]
**报告描述**
你需要针对漏洞进行描述，其中的信息包括详细描述，构建时的系统平台，与预期不符的错误点。

In your documents that after using` build/chcore/bin/musl-gcc` to compile a user-program into hello_chcore.bin and put it under directory `ramdisk`. 
But it seems that it should be named as: `hello_world.bin` after `make qemu-grade`.

<img width="560" alt="Screenshot 2024-11-23 at 20 53 00" src="https://github.com/user-attachments/assets/a2614110-e4a1-4ede-ae4f-9ce205eafde5">

<img width="334" alt="Screenshot 2024-11-23 at 20 59 42" src="https://github.com/user-attachments/assets/b001d58f-2061-47de-8d2b-c8c531c4bad2">

After we renamed the bin into `hello_world.bin`
<img width="268" alt="Screenshot 2024-11-23 at 20 53 53" src="https://github.com/user-attachments/assets/e417168b-71e4-47cb-9a5f-0fd561ebe841">

We can have that

<img width="589" alt="Screenshot 2024-11-23 at 20 55 28" src="https://github.com/user-attachments/assets/c13ae489-f152-41c0-b951-cab9dc0cfc92">

<img width="340" alt="Screenshot 2024-11-23 at 21 01 03" src="https://github.com/user-attachments/assets/1f6fbf42-27e3-4aa3-adc1-68b6ee44b188">

I have done this after `git pull`.

It seems that problem is here, in `user/system-services/system-servers/procmgr/procmgr.c`: we just need to change the `hello_world_argv`

<img width="654" alt="Screenshot 2024-11-23 at 21 32 01" src="https://github.com/user-attachments/assets/7da7469f-0a2f-4b4b-9e57-fbaea3011d4b">

I am too lazy to fork and make a pull request, I think the following modification is one of the plan to get `hello_chcore.bin` into use. 

<img width="539" alt="Screenshot 2024-11-23 at 22 19 08" src="https://github.com/user-attachments/assets/10e823a7-8d33-44b4-9167-9d81f8b8bfce">

**Comment by sjtugjy** [comment]
@mumupika Have you solved it?

**Comment by mumupika** [comment]
Yes, after your team has update the libc.

**Comment by ToolmanP** [comment]
Sorry for stale docs. Fix in 839603a6944054fe6058faca373c9931336e43ff
