### ISSUE TITLE
[BUG] Lab3: make failure due to musl-libc overriding on macOS

### ISSUE THREAD

**Issue by MisakaVan** [SJTU-IPADS/OS-Course-Lab#64]
**报告描述**
在`Lab3`执行`make`报错，无法正常编译

**复现方式**
环境：MacOS `ipads/oslab:24.09`的Devcontainer
我在全新clone的仓库和自己的仓库里都能复现同样的错误。
1. 执行 `git submodule update --init --recursive`
2. `cd Lab3`
3. `make`

出现的错误信息（节选）
```
/workspaces/ChCore-debug/Lab3/user/chcore-libc/libchcore/cmake/do_override_dir.sh: line 25: [[[[: command not found
```

这个`[[[[`是在这个commit中引入的，看上去是直接将`[`替换成了`[[`导致把`[[`变成了`[[[[`。
https://github.com/SJTU-IPADS/OS-Course-Lab/commit/4dff3f96c8a1902c5aee6fe66f9fa6f6157402cd#diff-fab1668794f254f76d994f838a59844f36216372839888012834a3b38df2bd5dR25

但是将脚本中这一行更改后
```
if [[ $1 != /* ]] || [[ $2 != /* ]]; then
```

再次make仍然会报错:

```
mv: '/workspaces/ChCore-debug/Lab3/user/chcore-libc/musl-libc/src/thread/aarch64/__unmapself.s' and '/workspaces/ChCore-debug/Lab3/user/chcore-libc/musl-libc/src/thread/aarch64/__unmapself.s.bak' are the same file
```

以上是`Thirdparty/musl-libc`在`dd1e63c3`的结果（`git submodule update`以后就自动是这个commit）

切换到`Thirdparty/musl-libc`的不同版本测试(`v1.2.5`、`v1.2.3`、`v1.2.1`）

```
stu@Chcore:/workspaces/ChCore-debug/Thirdparty/musl-libc$ git reset --hard
stu@Chcore:/workspaces/ChCore-debug/Thirdparty/musl-libc$ git checkout v1.2.1
```

再次在Lab3进行make，报错信息变为

```
ln: failed to access '/workspaces/ChCore-debug/Lab3/user/chcore-libc/musl-libc/src/thread/aarch64/__unmapself.S': Invalid argument
```

---

应当检查`Lab3/user/chcore-libc/libchcore/cmake/do_override_dir.sh`以及`musl-libc/src/thread/aarch64/__unmapself.S`的override行为。

**Comment by MisakaVan** [comment]
1. `rm -rf Thirdparty/musl-libc/`
2. 重新`git submodule update --init --recursive`

`Thirdparty/musl-libc/src/thread/aarch64/__unmapself.S`有很诡异的行为：

理论上只存在`__unmapself.s`（小写后缀）而不存在`__unmapself.S`大写后缀，但是实际上无法创建`__unmapself.S`文件：

![79531733143026_ pic](https://github.com/user-attachments/assets/e4c6a596-4d1a-44a1-a777-425e4e8a6e13)

测试发现一些很诡异的行为，比如`__unmapself.s`和`__unmapself.S`似乎是同一个文件，尽管`ls`无法发现后者。

![79561733144590_ pic](https://github.com/user-attachments/assets/50f1a47b-5ecb-4c15-8332-d4788dab83d5)

---

在`Lab3/user/chcore-libc/libchcore/cmake/do_override_dir.sh`脚本里加了debug信息观察如何override `musl-libc/src/thread/aarch64/`目录。

```
(0)
--- [debug] Found new file /workspaces/ChCore-debug/Lab3/user/chcore-libc/libchcore/porting/overrides/src/thread/aarch64/CMakeLists.txt, target file /workspaces/ChCore-debug/Lab3/user/chcore-libc/musl-libc/src/thread/aarch64/CMakeLists.txt does not exist.
--- [debug] ln -sf -v /workspaces/ChCore-debug/Lab3/user/chcore-libc/libchcore/porting/overrides/src/thread/aarch64/CMakeLists.txt /workspaces/ChCore-debug/Lab3/user/chcore-libc/musl-libc/src/thread/aarch64/CMakeLists.txt
--- Overrided /workspaces/ChCore-debug/Lab3/user/chcore-libc/musl-libc/src/thread/aarch64/CMakeLists.txt with /workspaces/ChCore-debug/Lab3/user/chcore-libc/libchcore/porting/overrides/src/thread/aarch64/CMakeLists.txt

(1)
--- [debug] Found new file /workspaces/ChCore-debug/Lab3/user/chcore-libc/libchcore/porting/overrides/src/thread/aarch64/__thread_exit.S, target file /workspaces/ChCore-debug/Lab3/user/chcore-libc/musl-libc/src/thread/aarch64/__thread_exit.S does not exist.
--- [debug] ln -sf -v /workspaces/ChCore-debug/Lab3/user/chcore-libc/libchcore/porting/overrides/src/thread/aarch64/__thread_exit.S /workspaces/ChCore-debug/Lab3/user/chcore-libc/musl-libc/src/thread/aarch64/__thread_exit.S
--- Overrided /workspaces/ChCore-debug/Lab3/user/chcore-libc/musl-libc/src/thread/aarch64/__thread_exit.S with /workspaces/ChCore-debug/Lab3/user/chcore-libc/libchcore/porting/overrides/src/thread/aarch64/__thread_exit.S

(2)
--- [debug] Found new file /workspaces/ChCore-debug/Lab3/user/chcore-libc/libchcore/porting/overrides/src/thread/aarch64/__unmapself.S, target file /workspaces/ChCore-debug/Lab3/user/chcore-libc/musl-libc/src/thread/aarch64/__unmapself.S exists and is not a symlink.
--- [debug] mv /workspaces/ChCore-debug/Lab3/user/chcore-libc/musl-libc/src/thread/aarch64/__unmapself.S /workspaces/ChCore-debug/Lab3/user/chcore-libc/musl-libc/src/thread/aarch64/__unmapself.S.bak
--- [debug] ln -sf /workspaces/ChCore-debug/Lab3/user/chcore-libc/libchcore/porting/overrides/src/thread/aarch64/__unmapself.S /workspaces/ChCore-debug/Lab3/user/chcore-libc/musl-libc/src/thread/aarch64/__unmapself.S
--- Overrided /workspaces/ChCore-debug/Lab3/user/chcore-libc/musl-libc/src/thread/aarch64/__unmapself.S with /workspaces/ChCore-debug/Lab3/user/chcore-libc/libchcore/porting/overrides/src/thread/aarch64/__unmapself.S

(3)
--- [debug] Found deletion file /workspaces/ChCore-debug/Lab3/user/chcore-libc/libchcore/porting/overrides/src/thread/aarch64/__unmapself.s.del, should delete /workspaces/ChCore-debug/Lab3/user/chcore-libc/musl-libc/src/thread/aarch64/__unmapself.s
--- [debug] mv /workspaces/ChCore-debug/Lab3/user/chcore-libc/musl-libc/src/thread/aarch64/__unmapself.s /workspaces/ChCore-debug/Lab3/user/chcore-libc/musl-libc/src/thread/aarch64/__unmapself.s.bak
mv: '/workspaces/ChCore-debug/Lab3/user/chcore-libc/musl-libc/src/thread/aarch64/__unmapself.s' and '/workspaces/ChCore-debug/Lab3/user/chcore-libc/musl-libc/src/thread/aarch64/__unmapself.s.bak' are the same file
```

1. （根据上面的`(2)`）脚本认为`musl-libc/src/thread/aarch64/__unmapself.S`存在，需要用`overrides/src/thread/aarch64/__unmapself.S`替换。先将前者移动到`__unmapself.S.bak`然后创建从`__unmapself.S`指向新文件的符号连接。但是实际上这个前者`musl-libc/src/thread/aarch64/__unmapself.S`不应该存在，override应该的行为只是创建一个`__unmapself.S`的符号链接。
2. (3)脚本尝试删除`musl-libc/src/thread/aarch64/__unmapself.s`并报错。不清楚为什么会认为`musl-libc/src/thread/aarch64/`目录下的`__unmapself.s`和`__unmapself.s.bak`是同一个文件，因为后者这时应该还不存在。
在报错退出后，`usl-libc/src/thread/aarch64/`下是这样：

![5471733144387_ pic](https://github.com/user-attachments/assets/438b409c-c906-4e99-a5d6-ac5b1226d5f6)

并不知道小写后缀的`__unmapself.s`、`__unmapself.s.bak`在哪里。

---

结合上文所述(`musl-libc/src/thread/aarch64/`下的`__unmapself.s`和`__unmapself.S`似乎是同一个文件）,
就可以解释脚本的行为：
1. 将`musl-libc`库的`__unmapself.S` mv到 `__unmapself.S.bak`，但也可以看成是`__unmapself.s` mv到 `__unmapself.s.bak`。
2. 创建从`__unmapself.S`符号链接到新的文件。
3. 尝试删除`__unmapself.s`，方式同样是`__unmapself.s` mv到 `__unmapself.s.bak`。
4. `__unmapself.s` 和 `__unmapself.s.bak`都存在，1和3导致`mv: ... are the same file`错误

![5481733146018_ pic](https://github.com/user-attachments/assets/affdce89-ad4c-4e68-8b92-c2a7faed78dc)

---

如果保持其他操作不变，只是将`overrides/src/thread/aarch64/__unmapself.S`重命名为`overrides/src/thread/aarch64/__unmapself123.S`，然后开始make就不会有override错误。（后续链接会报错）
这是因为此时“向`musl-libc`添加新文件`__unmapself123.S`”和“删除`__unmapself.s`”不会因为这个诡异的后缀名行为互相影响。

```
stu@Chcore:/workspaces/ChCore-debug/Lab3$ git mv user/chcore-libc/libchcore/porting/overrides/src/thread/aarch64/__unmapself.S user/chcore-libc/libchcore/porting/overrides/src/thread/aarch64/__unmapself123.S 
stu@Chcore:/workspaces/ChCore-debug/Lab3$ make

(passes override)
```

因此可以说明是`Thirdparty/musl-libc/src/thread/aarch64/__unmapself.S`的诡异行为造成的。不清楚这是我环境的特例还是`git submodule update`导致的普遍存在的原因。

---

## 可行的Fix

用以下方法可以正常编译

1. 重置`musl-libc`库。在项目根目录 `cd Thirdparty && rm -rf musl-libc/` 然后重新 `git submodule update --init --recursive`
2. 移动到行为异常的目录，删除并重新创建`__unmapself.s`:
```
stu@Chcore:/workspaces/ChCore-debug/Thirdparty/musl-libc/src/thread/aarch64$ cat __unmapself.s > tmp.txt
stu@Chcore:/workspaces/ChCore-debug/Thirdparty/musl-libc/src/thread/aarch64$ rm __unmapself.s 
stu@Chcore:/workspaces/ChCore-debug/Thirdparty/musl-libc/src/thread/aarch64$ rm __unmapself.S
rm: cannot remove '__unmapself.S': No such file or directory
stu@Chcore:/workspaces/ChCore-debug/Thirdparty/musl-libc/src/thread/aarch64$ cat tmp.txt > __unmapself.s
```
3. 在`Lab3`执行`make`。

**Comment by MisakaVan** [comment]
## 可行的Fix

用以下方法可以正常编译

1. 重置`musl-libc`库。在项目根目录 `cd Thirdparty && rm -rf musl-libc/` 然后重新 `git submodule update --init --recursive`
2. 移动到行为异常的目录，删除并重新创建`__unmapself.s`:
```
stu@Chcore:/workspaces/ChCore-debug/Thirdparty/musl-libc/src/thread/aarch64$ cat __unmapself.s > tmp.txt
stu@Chcore:/workspaces/ChCore-debug/Thirdparty/musl-libc/src/thread/aarch64$ rm __unmapself.s 
stu@Chcore:/workspaces/ChCore-debug/Thirdparty/musl-libc/src/thread/aarch64$ rm __unmapself.S
rm: cannot remove '__unmapself.S': No such file or directory
stu@Chcore:/workspaces/ChCore-debug/Thirdparty/musl-libc/src/thread/aarch64$ cat tmp.txt > __unmapself.s
```
3. 修改`Lab3/user/chcore-libc/libchcore/cmake/do_override_dir.sh`的25行
```
if [[ $1 != /* ]] || [[ $2 != /* ]]; then
```
4. 在`Lab3`执行`make`。

**Comment by sjtugjy** [comment]
这问题应该和MAC相关。@Ayanami1314 能否检查下。我自己的mac上甚至多线程编译ChCore会报错，改成单线程编译OK。

**Comment by Ayanami1314** [comment]
> 这问题应该和MAC相关。@Ayanami1314 能否检查下。我自己的mac上甚至多线程编译ChCore会报错，改成单线程编译OK。

我这里没有mac的机器? 
btw, 我这里刚刚重现了这个bug（Ubuntu 24.04 x86-64）我再试试其他情况

**Comment by Ayanami1314** [comment]
在ubuntu上似乎是权限问题

> 我这里刚刚重现了这个bug
> 1. 执行 git submodule update --init --recursive
> 2. cd Lab3
> 3. make

这个时候新的submodule文件的权限会很奇怪, 出现类似的问题
此时如果在容器外直接给 `sudo chmod -R 777` 就能正常编译

**Comment by MisakaVan** [comment]
> Permission denied

权限不足和我遇到的应该不是同一个问题。

> 比如`__unmapself.s`和`__unmapself.S`似乎是同一个文件，尽管`ls`无法发现后者。

我在MacOS的容器外（使用原生终端）下载submodule以后也出现 “`cd Thirdparty/musl-libc/src/thread/aarch64/ && ll __unmapself.S`能发现不应该存在的`__unmapself.S`文件”这个问题

在Windows的Ubuntu20.04虚拟机里也测试了一下，运行`git submodule update --init --recursive`以后是没有这种问题的，`make`也可以直接通过（而且也不会报`[[[[`的错误）。

也许是macOS和submodule的一些问题

**Comment by MisakaVan** [comment]
我刚才才知道macOS的文件系统默认是不区分大小写的🤨
https://discussions.apple.com/thread/251191099
https://stackoverflow.com/questions/25575463/git-macos-case-sensitive-overwrite-issues

例如
```
touch foo.bar && ll foo.bar && ll foo.Bar && ll Foo.Bar
```
完全可以正常运行，也可以解释上述奇怪的文件系统行为。在容器内外的行为也因此应该是一样的。

---

回顾上述有问题的override过程。以下用“老”指submodule里的文件，“新”指overriding文件夹里的文件。
1. **把新的`__unmapself.S`放进老文件夹里。** 如果老文件夹里`__unmapself.S`不存在，就创建`__unmapself.S`的符号链接指向新的`__unmapself.S`；否则，（实际上检测到了`__unmapself.s`存在）先将老的`__unmapself.S`移动到`__unmapself.S.bak`然后再创建符号链接。
2. **删除老的`__unmapself.s`。** 把老的`__unmapself.s`移动到`__unmapself.s.bak`。

然而macOS的文件系统上（默认）不能只通过大小写的差异来在同一个目录下保存/区分这些文件。

在所有的override过程中，也应该只有这一对文件出现了这种大小写混淆的情况。

如果要兼容macOS的文件系统，可能可以
- 更改新的`__unmapself.S`文件名和相应的CMake配置
- 也许可以直接用一份新的`__unmapself.s`替换老的`__unmapself.s`？（我没有细看这里是否一定要分成两个文件，删掉旧的并且导入新的）

**Comment by ToolmanP** [comment]
在#40已经更改了 现在应当没有大小写冲突的名字

**Comment by ToolmanP** [comment]
已修复，现在可以正常build了 @MisakaVan 麻烦可以帮忙测试一下吗？

**Comment by MisakaVan** [comment]
@ToolmanP 我这里测试下来OK
